# Generated by Django 3.0.1 on 2020-01-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20200104_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderd_date',
            new_name='ordered_date',
        ),
    ]
